---
title: "First Knit"
author: "Wayne Jarvis"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended William J. Pete Knight High School in 2021. I graduated as class of 2025. English was easier for me than math. Math is easily my least favorite subject. I did the best in P.E and English. I was an athlete, excelling in tennis and soccer.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
My computer is a Gigabyte 5 which has Windows 11 on it. It's a gaming laptop which was built in 2022. I consider myself a solid seven when it comes to computers. Although I'm not an expert, I know my way around the internet fairly well. The internet over here is excellent most of the time. We recently had an outage, but those are few and far between.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddy s call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I am fine with my full name, initials, and nicknames. I've been called many things in my lifetime, so I am not offended by an epithet.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I am aiming for a M.A. in Psychology, particularly specializing in the marriage and family field. I want to be a therapist for couples, parents, and children. Psychology is of the greatest interest to me for this reason. I was also inspired by teachers at my high school, one who was in the field. Aside from an M.A., I also want to be a certified counselor. This is because I think helping the youth is a wonderful thing. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have been to Brazil twice in my lifetime. I am half Brazilian, and went to visit my family; both times I was an infant. If I were ever drafted, I would like to go into the Marines. This is because I find them to be the most intense, admirable, and formidable branch.  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
This is my first math class and I am taking it to support my IGETC requirements. There wasn't any room available for another math class so I went with the next best option. I need to attain a C or higher in order to support my future endeavors. I would like to have a higher grade, but need to become more comfortable with this software first. My plan is to transfer to a four year university, particularly CSUN. I'll undergo post graduate study and become a certified therapist in California
   
 






  




